#!/usr/bin/env bash

if [[ -z $1 ]]; then
  echo "too few arguments" >&2
  exit 1
elif [[ -n $2 ]]; then
  echo "too many arguments" >&2
  exit 1
fi

LOG_DIR=$1

tar -czf $(date "+/var/log/logs_archive_%Y%m%d_%H%M%S.tar.gz") $LOG_DIR
